### ISSUE TITLE
Where are the XSD files?

### ISSUE THREAD

**Issue by peterjc** [bioxsd/bioxsd#1]
Hi - great to see bioxsd on GitHub.

Perhaps you're still working on this, but I can't see the actual schema files here yet.

https://github.com/bioxsd/bioxsd/tree/master/release1.1 contains only a `README.md` file which mentions `BioXSD-1.1.xsd` with a link to http://bioxsd.org/BioXSD-1.1 and http://bioxsd.org/BioXSD-1.1.xsd which are currently both:

```
<xs:schema targetNamespace="http://bioxsd.org/BioXSD-1.1" version="1.1.3" elementFormDefault="qualified" attributeFormDefault="unqualified">
```

Likewise, https://github.com/bioxsd/bioxsd/tree/master/release1.0 contains only a `README.md` file which mentions `BioXSD-1.0.xsd` with links to http://bioxsd.org/BioXSD-1.0 and http://bioxsd.org/BioXSD-1.0.xsd

As an aside, at the time of writing http://bioxsd.org/BioXSD-1.0.xsd is:

```
<xs:schema version="1.0.0" targetNamespace="http://bioxsd.org/BioXSD-1.0" elementFormDefault="qualified" attributeFormDefault="unqualified" xml:lang="en"><!--
```

On the other hand, http://bioxsd.org/BioXSD-1.0 is currently:

```
<xs:schema version="1.0.2" targetNamespace="http://bioxsd.org/BioXSD-1.0" elementFormDefault="qualified" attributeFormDefault="unqualified">
```

I would hope to see these checked into GitHub as revisions of `BioXSD-1.0.xsd` (making it easy to see the changes from 1.0.0 to 1.0.1 to 1.0.2 etc).

**Comment by matuskalas** [comment]
Thank you @peterjc for your interest.

As you suggested, all releases of BioXSD have been transferred to GitHub as successive revisions (806474a), so it's now much easier to see the changes between versions.

**Comment by peterjc** [comment]
Thank you :)
